name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
  MONGO_USERNAME: superuser
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    
jobs:
    unit-testing:

        name: Unit Testing
# this will enable us to use a service container for mongo and run the unit tests, this will ensure that the unit tests are run in a consistent environment and that we have a clean slate for each test run, as the service container will be recreated for each test run.
# and also by this we're not using prod mongo instance for testing, we're using a non-prod mongo instance which is running in a container, this will ensure that we don't have any issues with the prod mongo instance
        services:
          mongo:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
        env:
          MONGO_URI: mongodb://localhost:27017/superData
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v4
          with:
            node-version: 20
        
        - name: Cache Node Modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    

    code-coverage:
      name: Code-Coverage-Result
      runs-on: ${{ matrix.operating-system }}
# running the code coverage job in a container to ensure 
# that the code coverage is generated in a consistent environment and to avoid any issues related to dependencies or configurations on the host machine.
# but with that in place the service container is just another container running beside the job container, so you dont need to map the ports and you can 
# access the service container using the service name as the hostname and the default port of the service, in this case mongo:27017
      container:
        image: node:${{ matrix.node-version }}

      services:
          mongo:
            image: siddharth67/mongo-db:non-prod
            options:
              --name mongo  # this is important to set the name of the service container so that you can use it as the hostname in the job container to access the service container, in this case mongo:27017
            # ports:    ## this will be in place by default as both the job container and the service container share teh same network, so you can access the service container using the service name as the hostname and the default port of the service, in this case mongo:27017
            #   - 27017:27017
      env:
          MONGO_URI: mongodb://mongo:27017/superData ## using the service name as the hostname and the default port of the service, in this case mongo:27017
          MONGO_USERNAME: non-prod-user
          MONGO_PASSWORD: non-prod-password
      strategy:
        matrix:
          node-version: [ 20]
          operating-system: [ubuntu-latest]
          exclude:
            - node-version: 18
              operating-system: macos-latest
      steps:
        - name: checkout repository
          uses: actions/checkout@v4
        
        # - name: setup nodejs version
        #   uses: actions/setup-node@v4
        #   with:
        #     node-version: ${{ matrix.node-version }}

        - name: Cache Node Modules
          uses: actions/cache@v3
          with:
            path: node_modules
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    
        - name: install dependencies
          run: npm install

        - name: run code coverage
          continue-on-error: true
          run: npm run coverage
        
        - name: Archive Code Coverage Result
          uses: actions/upload-artifact@v4
          with:
            name: Code-Coverage-Result-${{ matrix.operating-system }}-Node-${{ matrix.node-version }}
            path: coverage
            retention-days: 5

    containerization:
      name: Docker Build and Push
      runs-on: ubuntu-latest
      needs: [unit-testing, code-coverage]
      steps:
        - name: checkout repository
          uses: actions/checkout@v4
        
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ vars.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Login to GHCR
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.repository_owner }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build Docker Image
          uses: docker/build-push-action@v3
          with:
            context: .
            push: false
            tags: ${{ vars.DOCKER_USERNAME }}/solar-system-app:${{ github.sha }}
        
        - name: Docker Test
          run: |
            docker images
            docker run -d --name solar-system-app \
            -p 3000:3000 \
            -e MONGO_URI=${{ env.MONGO_URI }} \
            -e MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            -e MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
            ${{ vars.DOCKER_USERNAME }}/solar-system-app:${{ github.sha }}
            
            sleep 3

            echo "Testing Docker Container... using curl command to check if the application is running"  
            curl -sf http://127.0.0.1:3000/live
        
        - name: Push Contiainer Image to DockerHub and GHCR
          uses: docker/build-push-action@v3
          with:
            context: .
            push: true
            tags: | 
              ${{ vars.DOCKER_USERNAME }}/solar-system-app:${{ github.sha }}
              ghcr.io/${{ github.repository_owner }}/solar-system-app:${{ github.sha }}


    dev-deploy:
      needs: containerization
      runs-on: ubuntu-latest
      steps:
        - name: checkout repository
          uses: actions/checkout@v6

        - name: Install kubectl
          uses: azure/setup-kubectl@v3
          with:
            version: '1.30'

        - uses: azure/k8s-set-context@v4
          with:
            method: service-account
            k8s-url: ${{ secrets.STAGING_K8S_URL }}
            k8s-secret: ${{ secrets.STAGING_K8S_SA_TOKEN }}

        
        - name: Setup Kubeconfig
          run: |
            kubectl version --short
            echo -----------
            kubectl get nodes